version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:3.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  jobs:
    depends_on:
      - "postgres"
      - "redis"
      - "app"
      - "elasticsearch"
    build:
      context: ./back_tweet
    command: bash start_jobs.sh
    volumes:
      - ./back_tweet:/LabSixTweet
      - box:/box
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200

  app:
    depends_on:
      - "postgres"
      - "redis"
      - "elasticsearch"
    build:
      context: ./back_tweet
      dockerfile: dockerfile
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - ./back_tweet:/LabSixTweet
      - box:/box
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200

  website:
    build:
      context: ./client_tweet
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - './client_tweet:/LabSixTweet_client'
    environment:
      - NODE_ENV=development

  elasticsearch:
    image: "elasticsearch:5"
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - Des.network.host=0.0.0.0

volumes:
  redis:
  postgres:
  box:
  elastic: