---
development:
  cloud_name: dua06iuoo
  api_key: '497163218135123'
  api_secret: sCMdxXALkw0A3FwH_gQ1RoDFnlg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dua06iuoo
  api_key: '497163218135123'
  api_secret: sCMdxXALkw0A3FwH_gQ1RoDFnlg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dua06iuoo
  api_key: '497163218135123'
  api_secret: sCMdxXALkw0A3FwH_gQ1RoDFnlg
  enhance_image_tag: true
  static_file_support: false
